export enum AccessPermission {
    CREATE_USER = 'CREATE_USER',
    VIEW_USERS = 'VIEW_USERS',
    DELETE_USER = 'DELETE_USER',
    UPDATE_USER = 'UPADTE_USER',

    CREATE_ROLE = 'CREATE_ROLE',
    VIEW_ROLES = 'VIEW_ROLES',
    DELETE_ROLE = 'DELETE_ROLE',
    UPDATE_ROLE = 'UPDATE_ROLE',

    CREATE_PERMISSION = 'CREATE_PERMISSION',
    VIEW_PERMISSIONS = 'VIEW_PERMISSIONS',
    DELETE_PERMISSION = 'DELETE_PERMISSION',
    UPDATE_PERMISSION = 'UPDATE_PERMISSION'
}